### ISSUE TITLE
Uncaught Error: Cannot find module 'quokka-atom/build/extension/dist/wallaby/client'

### ISSUE THREAD

**Issue by egauci** [wallabyjs/atom-quokka#1]
[Enter steps to reproduce:]

1. ... Install atom-quokka either from preferences or via apm. The package appears to install but throws an error on startup.

**Atom**: 1.19.4 ia32
**Electron**: 1.6.9
**OS**: Microsoft Windows 7 Enterprise 
**Thrown From**: [atom-quokka](https://github.com/wallabyjs/atom-quokka) package 1.0.8

### Stack Trace

Uncaught Error: Cannot find module 'quokka-atom/build/extension/dist/wallaby/client'

```
At module.js:472

Error: Cannot find module 'quokka-atom/build/extension/dist/wallaby/client'
    at Module._resolveFilename (module.js:470:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.19.4/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.19.4/resources/app/src/module-cache.js:354:58)
    at Module.require (~/AppData/Local/atom/app-1.19.4/resources/app/static/index.js:40:43)
    at require (~/AppData/Local/atom/app-1.19.4/resources/app/src/native-compile-cache.js:66:33)
    at /packages/atom-quokka/lib/quokka.js:12:29)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)
```

### Commands

```
```

### Non-Core Packages

```
atom-beautify 0.30.5 
atom-material-syntax-dark 1.0.0 
atom-material-ui 2.0.4 
atom-prettify 0.1.3 
atom-quokka 1.0.8 
atom-typescript 11.0.7 
atom-ungit undefined 
atomatigit undefined 
busy-signal 1.4.3 
file-icon-supplement undefined 
flow-ide 1.8.1 
highlight-selected 0.13.1 
intentions 1.1.5 
language-babel 2.73.0 
linter 2.2.0 
linter-eslint 8.2.1 
linter-flow 5.6.1 
linter-ui-default 1.6.8 
monokai-seti 0.9.0 
open-recent 5.0.0 
pigments 0.40.2 
prettier-atom 0.38.0 
pretty-json 1.6.4 
readonly 0.2.0 
to-base64 0.5.2 
toggle-read-only 0.1.8 
tree-view-git-status 1.4.0 
```

**Comment by ArtemGovorov** [comment]
Looks like the installation failed to download a required dependency. Please try to re-install the extension. If it doesn't help, please uninstall the extension, run the installation with `apm install atom-quokka` command and share its execution output.

**Comment by egauci** [comment]
Does the installation download using https from a node script? If it does that will fail in my environment and there is nothing I can do about it. I'm behind a corporate firewall/proxy that intercepts and re-encrypts all ssl traffic. Node will fail because the certificate will be invalid. The only solutions I know are to either use http or relax the ssl security setting.

Two things: 1) I just verified that it installs correctly at home on my Mac.
2) I will try the apm install again on Thursday at work, but I did do it today and I don't remember anything out of the ordinary. It looked like the installation worked, but then when I started Atom I got the same error.

Thank you for replying so quickly.

**Comment by ArtemGovorov** [comment]
> Does the installation download using https from a node script?

Correct, it is exactly what it does.

We are using the [`download` module](https://github.com/kevva/download) and it [respects proxy setting set in process.env](https://github.com/kevva/get-proxy/blob/master/index.js#L6). So you may try setting those in your [Atom Init Script](http://flight-manual.atom.io/hacking-atom/sections/the-init-file/):

```
process.env.https_proxy = 'your company https proxy'
process.env.http_proxy = 'your company http proxy'
```

**Comment by egauci** [comment]
Proxy env settings are correct already, or nothing else would work (npm for example). However, for  those I also have to disable strict ssl.  I just did some research and maybe this:

    process.env.NODE_TLS_REJECT_UNAUTHORIZED = "0";

will help. I will try Thursday morning and report back.

**Comment by egauci** [comment]
Yes! That worked. Adding the NODE_TLS_REJECT_UNAUTHORIZED statement to init.coffee allowed the installation to go through.

Thank you for your help! Feel free to close this issue.

**Comment by ArtemGovorov** [comment]
Awesome, thanks for the update!
