### ISSUE TITLE
Run Quokka as soon as file opens

### ISSUE THREAD

**Issue by oakley808** [wallabyjs/atom-quokka#3]
Great plugin!
Is it possible to have quokka automatically evaluate a file as the file is opened? Currently I have to hit `Command-K Q` after opening every file.

**Comment by ArtemGovorov** [comment]
Thanks!
It's not possible at the moment, I also don't think everyone would like to run Quokka on each opened file, so we may implement the feature behind a flag/setting.

**Comment by oakley808** [comment]
That makes sense. I was thinking it could be like a code linter that would run every time you open files of a certain type/extension.
