### ISSUE TITLE
Uncaught TypeError: Cannot read property 'text' of undefined ...

### ISSUE THREAD

**Issue by pratiksolim** [wallabyjs/atom-quokka#4]
I am getting following error while writing in JS syntax:

`Uncaught TypeError: Cannot read property 'text' of undefined
    at d._hideStatusIndicator (/.atom/packages/atom-quokka/node_modules/quokka-atom/build/quokka.js:1)
    at d._updateStatus (/.atom/packages/atom-quokka/node_modules/quokka-atom/build/quokka.js:1)
    at /.atom/packages/atom-quokka/node_modules/quokka-atom/build/quokka.js:1`

**Comment by ArtemGovorov** [comment]
What is your version of Atom?

**Comment by ArtemGovorov** [comment]
I can't reproduce the issue, but have added some checks to make sure the error can not happen anymore. Please update to v1.0.32 to see if it helps.
