### ISSUE TITLE
Error: ​​Cannot find module 'ramda'​​ -  VSCode 1.18.1 -  Quokka.js 1.0.81

### ISSUE THREAD

**Issue by eacevedof** [wallabyjs/atom-quokka#5]
It was working fine. till i decided to use ramda 

​​​​Quokka #1 (node: v8.9.1)​​​​
​​​​
​​Cannot find module 'ramda'​​
  at ​​​Function.Module._resolveFilename​​​ ​module.js:536​
  at ​​​Function.Module._load​​​ ​module.js:466​

package.json:
... 
  "dependencies": {
    "eslint": "^4.8.0",
    "global": "^4.3.2",
    "lodash": "^4.17.4",
    "ramda": "^0.25.0"
  },

code:

```
//013_pipeoperator.js 2.1.0
//https://youtu.be/dYQIkV2L-eg?t=728
const R = require("ramda")
const _ = require("lodash")

const fn_doublesay = sString => sString.concat(",").concat(sString)
const fn_appendchar = (c,str) => (str != undefined)?str.concat(c):""
//const fn_exclaim = sString => fn_appendchar("!",sString)

const sGreet = R.pipe(
    fn_doublesay,
    _.capitalize,
    str => fn_appendchar("!",str)
)("Hi 5")

console.log(sGreet)
```

![image](https://user-images.githubusercontent.com/2829142/33524942-f0e14ca4-d825-11e7-9dca-2c0d8acff5d7.png)

**Comment by ArtemGovorov** [comment]
This means that `ramda` is not installed in your project. Try running `npm i ramda` in your project, or checking that `node_modules/ramda` does exist. If the module is installed, please share a sample repo where we could reproduce the issue.

**Comment by eacevedof** [comment]
^^ Ramda is installed because my script works fine.
![image](https://user-images.githubusercontent.com/2829142/33525362-2c4e9dde-d82e-11e7-83a0-a2b54f5212b1.png)
Result:
![image](https://user-images.githubusercontent.com/2829142/33525376-896e6f1c-d82e-11e7-9de3-30624eea7d89.png)

**Comment by ArtemGovorov** [comment]
Hmm, interesting. If I 
- create an empty project, 
- run `npm init` in it,
- run`npm i ramda lodash`, 
- create new Quokka file,
- and then paste your file content, 

everything is working for me. Could you please try the steps above (for anew project), and if it's working (meaning that the issue may be your project specific), could you please share a sample repo where we could reproduce the issue?

**Comment by eacevedof** [comment]
I followed the steps you mention.  It does not work either.

The original file is here.  Did you test it in visual studio code?. 
https://github.com/eacevedof/prj_funtionaljs/blob/master/funfunfunction/013_pipeoperator.js

![image](https://user-images.githubusercontent.com/2829142/33525597-27792248-d833-11e7-8671-78f65a6ac35f.png)

**Comment by ArtemGovorov** [comment]
Do you have multiple folders/projects opened in a single workspace? From your second screenshot it looks like it. If so, the issue may be that Quokka is trying to run a context of your other opened project. Try using the `Quokka.js: Select Workspace Folder` command (`Cmd/Ctrl + Shift + P`) and select the correct active project.

**Comment by ArtemGovorov** [comment]
Also we have just published a new version (1.0.83) with improved folder/project resolution. So now if you have multiple folders in your workspace and are running Quokka on a existing file in one of the projects, Quokka will automatically resolve the correct context (without using the `Quokka.js: Select Workspace Folder` command). 

Note that if you are creating a new scratch Quokka file (created with `Cmd/Ctrl + K, J`), then you may still need to use the `Quokka.js: Select Workspace Folder` command, if you'd like the Quokka file to run in a context of a specific project (if you have multiple projects opened in your workspace).

**Comment by eacevedof** [comment]
It works now. Thnx. Im using version 1.0.84

![image](https://user-images.githubusercontent.com/2829142/33648499-7a006c50-da5a-11e7-9f08-69f46252cc41.png)

**Comment by ArtemGovorov** [comment]
Awesome, thanks for the update!
