### ISSUE TITLE
Installation error - Cannot convert Undefined or Null to Object.

### ISSUE THREAD

**Issue by YourFriendChooly** [wallabyjs/atom-quokka#6]
Hi, I'm trying to install Quokka via Atom and am receiving the following error:

npm ERR! Darwin 15.6.0
npm ERR! argv "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/joenovak/.atom/.apm/.apmrc" "--userconfig" "/Users/joenovak/.atom/.apmrc" "install" "/private/var/folders/rg/fspcfp_17r9ghfw3mm4qcnqm0000gn/T/d-11806-453-8cwuiz.9ttke29/package.tgz" "--runtime=electron" "--target=1.6.15" "--arch=x64" "--global-style"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10

npm ERR! Cannot convert undefined or null to object
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /private/var/folders/rg/fspcfp_17r9ghfw3mm4qcnqm0000gn/T/apm-install-dir-11806-453-1p3mpb5.zoh4r6bt9/npm-debug.log

Also, when I look for the npm-debug.log file listed above, it's nowhere to be found.

**Comment by ArtemGovorov** [comment]
It is/was a global issue with npm, see https://github.com/npm/npm/issues/9896#issuecomment-355773447. Try again now, or a bit later.
